version: "3.0"
services:
  ckb:
    image: tockb/ckb-dev
    ports:
      - "8114:8114"
  ckb-indexer:
    image: tockb/ckb-indexer
    ports:
      - "8116:8116"
    environment:
      - RUST_LOG=info
    command: ckb-indexer -s /tmp/ckb-indexer-test -c http://ckb:8114 -l 0.0.0.0:8116
    depends_on:
      - ckb
  geth:
    image: tockb/geth-priv
    ports:
      - "8545:8545"
