version: "3.0"
services:
  ckb:
    image: tockb/ckb-dev:v0.36.0
    ports:
      - "8114:8114"
  ckb-indexer:
    image: tockb/ckb-indexer
    ports:
      - "8116:8116"
    environment:
      - RUST_LOG=info
    command: ckb-indexer -s /tmp/ckb-indexer-test -c http://ckb:8114 -l 0.0.0.0:8116
    depends_on:
      - ckb
  geth:
    image: tockb/geth-priv:v1.9.23
    volumes:
    - geth-dag:/root/.ethash
    ports:
      - "8545:8545"

volumes:
  geth-dag:
